package com.app1.utils;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sudheer' at '11/26/16 6:20 PM' with Gradle 2.2.1
 *
 * @author sudheer, @date 11/26/16 6:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
